#!/bin/bash
#
# Copyright (C) distroy
#


cd "$(dirname "${BASH_SOURCE[0]}")"
SOURCE_DIR="$PWD"


function ld_link()
{
    local src="$1"
    local dst="$2"

    mv "$dst" "$dst-bak-$(date +"%Y%m%d-%H%M%S")" &>/dev/null

    mkdir -p "$(dirname "$dst")"
    # ln -s "$src" "$dst"

    wsrc="$(cygpath -w "$src")"
    wdst="$(cygpath -w "$dst")"
    dir=
    test -d "$src" && dir=/d
    /cygdrive/c/windows/system32/cmd /c mklink $dir "$wdst" "$wsrc" &>/dev/null
}


# bin dir symbol link
ld_link $SOURCE_DIR/bin $HOME/local/cygwin/bin


# bin dir zshrc env
for i in $HOME/.zshrc; do
    cat >>"$i" <<EOF
# ld cygwin bin directory
export PATH=\$HOME/local/cygwin/bin:\$PATH
EOF
done


# minttyrc
ld_link $SOURCE_DIR/minttyrc $HOME/.minttyrc
