#!/bin/bash
#
# Copyright (C) distroy
#


SOURCE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd)"
ZSH_FILE=$HOME/.zshrc
RC_FILE=$HOME/.minttyrc


# bin dir symbol link
LOCAL_CYG=$HOME/local/cygwin
test -e $LOCAL_CYG/bin && mv $LOCAL_CYG/bin $LOCAL_CYG/bin.bak
ln -s $SOURCE_DIR/bin $LOCAL_CYG/bin


# bin dir zshrc env
cat >>$ZSH_FILE <<EOF
# please put it before source ld zshrc
export PATH=\$HOME/local/cygwin/bin:\$PATH
EOF


# minttyrc
test -e $RC_FILE && mv $RC_FILE ${RC_FILE}.bak
ln -s $SOURCE_DIR/minttyrc $RC_FILE

