#!/bin/bash
#
# Copyright (C) distroy
#


SOURCE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd)"
ZSH_FILE=$HOME/.zshrc
RC_FILE=$HOME/.minttyrc

export PATH=$SOURCE_DIR/bin:$PATH


# bin dir symbol link
LOCAL_CYG=$HOME/local/cygwin
mv $LOCAL_CYG/bin $LOCAL_CYG/bin.bak
lnk -s $SOURCE_DIR/bin $LOCAL_CYG/bin

# bin dir zshrc env
cat >>$ZSH_FILE <<EOF
# please put it before source ld zshrc
export PATH=\$HOME/local/cygwin/bin:\$PATH
EOF


# minttyrc
mv $RC_FILE ${RC_FILE}.bak
lnk -s $SOURCE_DIR/minttyrc $RC_FILE

