#!/bin/bash
#
# Copyright (C) distroy
#


function ld_atexit()
{
    test -e "$stderr" && rm "$stderr"
    test -e "$stdin" && rm "$stdin"
}


trap "ld_atexit" SIGHUP SIGINT SIGTERM
stderr=/tmp/gbk2utf8.$$.stderr
stdin=/tmp/gbk2utf8.$$.stdin

mkfifo $stderr
mkfifo $stdin

export LANG=zh_CN.gbk

iconv -c -f GBK -t UTF-8 <$stderr >&2 &
"$@" 2>$stderr | iconv -c -f GBK -t UTF-8
ld_atexit

exit $ret

