#!/usr/bin/env python

#
# Copyright (C) distroy
#

import os
import sys
import commands

widths = [1, 8, 8, 8, 11, 6, 8, 9]

def get_bcmd(arr):
    fmt = ''.join(['%%%ds' % i for i in widths]) + ' '
    return fmt % tuple(arr[: len(widths)])

def get_depth(depth):
    buff = ''

    for i in range(0, len(depth) - 1):
        if depth[i]:
            buff += ' |  '
        else:
            buff += '    '
    if len(depth):
        buff += ' \_ '

    return buff

def get_cmd(cmd):
    return cmd


def print_line(text):
    fd = sys.stdout.fileno()
    s = text

    try:
        w = int(os.environ['COLUMNS'])
        s = s[: w]
    except:
        pass

    os.write(fd, '%s\r\n' % s)


def parse_line(line):
    l = []

    start = 0
    for w in widths:
        end = start + w
        l.append(line[start: end].lstrip())
        start = end
    l.append(line[start: ].lstrip())

    return l

def print_head(head):
    buff = ''
    buff += get_bcmd(head)
    buff += get_cmd(head[-1])
    print_line(buff)

def print_tree(root, depth = []):
    text = root['text']
    childs = root['childs']

    buff = ''
    buff += get_bcmd(text)
    buff += get_depth(depth)
    buff += get_cmd(text[-1])
    print_line(buff)

    depth.append(1)
    for i in range(0, len(childs)):
        child = childs[i]
        if i == len(childs) - 1:
            depth.pop()
            depth.append(0)
        print_tree(child, depth)
    depth.pop()

def main():
    cmd = 'ps ' + ' '.join(sys.argv)
    (ret, output) = commands.getstatusoutput(cmd)
    if ret != 0:
        print (output)
        return ret

    lines = output.split("\n")

    head = parse_line(lines[0])
    if 'PPID' not in head:
        print (output)
        return 0

    tree = {}
    list = []

    for i in lines[1:]:
        text = parse_line(i)

        info = {}
        for i in range(0, len(head)):
            info[head[i]] = text[i]

        proc    = {'info': info, 'childs': [], 'root': 1, 'text': text}
        pid     = info['PID']

        try:
            fd = os.open('/proc/%s/cmdline' % pid, os.O_RDONLY)
            cmd = os.read(fd, 2048)
            cmd = cmd.replace('\0', ' ')
            text[-1] = cmd
        except:
            pass

        tree[pid] = proc
        list.append(proc)

    # make tree
    for proc in list:
        ppid = proc['info']['PPID']

        if ppid in tree.keys():
            parent = tree[ppid]
            parent['childs'].append(proc)
            proc['root'] = 0

    # print head
    print_head(head)
    # print tree
    for proc in list:
        if not proc['root']:
            continue

        print_tree(proc)

    return 0

if __name__ == '__main__':
    r = main()
    exit(r)

