#!/bin/bash
#
# Copyright (C) distroy
#


cd "$(dirname "${BASH_SOURCE[0]}")"
SOURCE_DIR="$PWD"
LD_GITRC=$HOME/gitconfig


# gitconfig
git config --global include.path ${SOURCE_DIR/#$HOME/\~}/gitconfig


