#!/bin/bash
#
# Copyright (C) distroy
#


LDRC="$(pwd)"
LD_ZSHRC=$HOME/.zshrc
LD_VIMRC=$HOME/.vimrc
LD_GITRC=$HOME/gitconfig


# zshrc
cat >>$LD_ZSHRC <<EOF
# ld zshrc
#ZSH=
#ZSH_DISABLE_GIT_DIRTY=true
source ${LDRC/#$HOME/\$HOME}/zshrc
unset LDRC ZSH ZSH_DISABLE_GIT_DIRTY
EOF


# vimrc
test -d ~/.vim && mv ~/.vim ~/.vim.$(date +%Y%m%d_%H%M%S)
ln -s $LDRC/vim ~/.vim

cat >>$LD_VIMRC <<EOF
" ld vimrc
source ${LDRC/#$HOME/\$HOME}/vimrc
EOF


# gitconfig
git config --global include.path ${LDRC/#$HOME/\~}/gitconfig


