#!/bin/bash
#
# Copyright (C) distroy
#


function ld_link()
{
    local src="$1"
    local dst="$2"

    if [ -e "$dst" ]; then
        mv "$dst" "$dst-bak-$(date +"%Y%m%d-%H%M%S")"
    fi
    mkdir -p "$(dirname "$dst")"
    ln -s "$src" "$dst"
}


if [[ "$0" == "${BASH_SOURCE[0]}" ]]; then
    for i in "$@"; do
        "$i/install"
    done
fi

