#! /usr/bin/env bash
#
# Copyright (C) distroy
#


cd "$(dirname "${BASH_SOURCE[0]}")"
SOURCE_DIR="$PWD"
source ../install


WRITE_FILE=$HOME/.vimrc

CLANG_FORMAT=$SOURCE_DIR/share/clang-format
YCM_CONF_PY=$SOURCE_DIR/share/ycm_extra_conf.py


# vimrc
cat >>$WRITE_FILE <<EOF
" ld vimrc
source ${SOURCE_DIR/#$HOME/\$HOME}/vimrc
EOF

mkdir -pv $HOME/.config/nvim
ln -sv $HOME/.vimrc $HOME/.config/nvim/init.vim

timestamp=$(date +%Y%m%d%H%M%S)
test -f $HOME/.clang-format && cp $HOME/.clang-format $HOME/.clang-format-$timestamp
cp -v $CLANG_FORMAT $HOME/.clang-format
test -f $HOME/.ycm_extra_conf.py && cp $HOME/.ycm_extra_conf.py $HOME/.ycm_extra_conf.py-$timestamp
cp -v $YCM_CONF_PY $HOME/.ycm_extra_conf.py

vim +PlugInstall +qa
