#! /usr/bin/env bash
#
# Copyright (C) distroy
#


cd "$(dirname "${BASH_SOURCE[0]}")"
SOURCE_DIR="$PWD"
source ../install


WRITE_FILE=$HOME/.vimrc


# vimrc
cat >>$WRITE_FILE <<EOF
" ld vimrc
source ${SOURCE_DIR/#$HOME/\$HOME}/vimrc
EOF

vim +PlugInstall
