"
" Copyright (C) distroy
"


if exists('g:ld_loaded_vimrc')
    finish
endif
let g:ld_loaded_vimrc = 1

if !exists('g:ld_user')
    let g:ld_user = 'distroy'
endif
if !exists('g:ld_email')
    let g:ld_email = 'distroy@163.com'
endif

if !exists('g:ld_tagshow')
    let g:ld_tagshow = 'tagbar'
endif


function! s:ld_source_directory(path)
    for l:file in split(globpath(a:path, '*.vim'), '\n')
        execute 'source' l:file
    endfor
endfunction


let g:ld_vim_path = fnamemodify(expand('<sfile>:p'), ':p:h')

execute 'source' g:ld_vim_path . '/plugin.vim'
call s:ld_source_directory(g:ld_vim_path . '/lib')
call s:ld_source_directory(g:ld_vim_path . '/libp')
