"
" Copyright (C) distroy
"


if !exists('g:ld') || type(g:ld) != v:t_dict
    let g:ld = {}
endif

if exists('g:ld.loaded_vimrc')
    finish
endif
let g:ld.loaded_vimrc = 1
let g:ld.vim_path = fnamemodify(resolve(expand('<sfile>:p')), ':h')

function! s:init_buffer()
    if !exists('b:ld') || type(b:ld) != v:t_dict
        let b:ld = {}
    endif
endfunction

autocmd BufNew,BufReadPre,BufWinEnter,BufNewFile * call <SID>init_buffer()

function s:ld_import_lib()
    let l:base = g:ld.vim_path . '/lib/'
    for l:idx in range(0, 100)
        let l:path = l:base . l:idx
        let l:idx += 1
        if isdirectory(l:path)
            for l:file in split(globpath(l:path, '*.vim'), '\n')
                execute 'source' l:file
            endfor
        endif
    endfor
endfunction

call s:ld_import_lib()
