"
" Copyright (C) distroy
"


if !exists('ld') || type(ld) != v:t_dict
    let ld = {}
endif

if exists('ld.loaded_vimrc')
    finish
endif
let ld.loaded_vimrc = 1
let ld_vim_path = fnamemodify(resolve(expand('<sfile>:p')), ':h')


function s:ld_import_lib()
    let l:base = g:ld_vim_path . '/lib/'
    for l:idx in range(0, 100)
        let l:path = l:base . l:idx
        let l:idx += 1
        if isdirectory(l:path)
            for l:file in split(globpath(l:path, '*.vim'), '\n')
                execute 'source' l:file
            endfor
        endif
    endfor
endfunction

call s:ld_import_lib()
