#!/bin/bash
#
# Copyright (C) distroy
#


SOURCE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd)"
WRITE_FILE=$HOME/.zshrc


# zshrc
cat >>$WRITE_FILE <<EOF
# ld zshrc
#ZSH=
#ZSH_DISABLE_GIT_DIRTY=true
source ${SOURCE_DIR/#$HOME/\$HOME}/zshrc
EOF

