#!/bin/bash
#
# Copyright (C) distroy
#


cd "$(dirname "${BASH_SOURCE[0]}")"
SOURCE_DIR="$PWD"
WRITE_FILE=$HOME/.zshrc


# zshrc
cat >>$WRITE_FILE <<EOF
# ld zshrc
source ${SOURCE_DIR/#$HOME/\$HOME}/zshrc
source ${SOURCE_DIR/#$HOME/\$HOME}/zshrc.key
EOF

git submodule update --init --recursive oh-my-zsh
cd oh-my-zsh
git checkout master
