# .zshrc
#
# Copyright (C) distroy
#


pushd $(dirname $0) &>/dev/null


# oh my zsh
ZSH=oh-my-zsh
DISABLE_AUTO_UPDATE=true

source "$ZSH/oh-my-zsh.sh"

unset ZSH
unset DISABLE_AUTO_UPDATE


for config_file (lib/*.zsh); do
    source $config_file
done
unset config_file


popd &>/dev/null
