# .zshrc
#
# Copyright (C) distroy
#


pushd $(dirname $0) &>/dev/null
LD_ZSH=$(pwd)


# oh my zsh
ZSH=$LD_ZSH/oh-my-zsh
DISABLE_AUTO_UPDATE=true

source "$ZSH/oh-my-zsh.sh"

unset ZSH
unset DISABLE_AUTO_UPDATE


function import () {
    local i
    for i in $@; do
        source $i
    done
}

import $LD_ZSH/env/*.zsh
import $LD_ZSH/lib/*.zsh

unset LD_ZSH
popd &>/dev/null
