# .zshrc
#
# Copyright (C) distroy
#


pushd $(dirname $0) &>/dev/null


# oh my zsh
ZSH=$(pwd)/oh-my-zsh
DISABLE_AUTO_UPDATE=true

source "$ZSH/oh-my-zsh.sh"

unset ZSH
unset DISABLE_AUTO_UPDATE


function import () {
    local i
    for i in $@; do
        source $i
    done
}

import env/*.zsh
import lib/*.zsh

popd &>/dev/null
