# .bashrc
#
# Copyright (C) distroy
#


pushd $(dirname $BASH_SOURCE) &>/dev/null


for (( i = 0; i <= 100; ++i )); do
    if [ ! -d lib/$i ]; then
        continue
    fi
    for j in $(echo lib/$i/*.bash); do
        source $j
    done
done
unset i j


popd &>/dev/null
