#!/bin/bash
#
# Copyright (C) distroy
#


cd "$(dirname "${BASH_SOURCE[0]}")"
SOURCE_DIR="$PWD"
WRITE_FILE=$HOME/.bashrc


# bashrc
cat >>$WRITE_FILE <<EOF
# ld bashrc
source ${SOURCE_DIR/#$HOME/\$HOME}/bashrc
EOF
